// @ts-nocheck
// Auto-generated by tauri-specta. DO NOT EDIT.


// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
/**
 * Write one log line. Called from the renderer via the Tauri command
 * bridge. Always best-effort: a write failure must never crash the
 * app, because this is the path the renderer takes when the app is
 * already crashing.
 */
async writeLogLine(line: LogLine) : Promise<Result<null, BdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("write_log_line", { line }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Flip the in-process diagnostic-logging flag. The Advanced
 * preferences "Enable diagnostic logging" switch is the only
 * legitimate caller. Per-session: not persisted, resets to `false`
 * on every app start.
 */
async setDiagnosticLogging(enabled: boolean) : Promise<Result<null, BdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_diagnostic_logging", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Read the current value of the in-process diagnostic-logging
 * flag. The frontend uses this to reflect the toggle's actual
 * state on mount (e.g. after a window reload that would otherwise
 * lose the local React state).
 */
async isDiagnosticLoggingEnabled() : Promise<Result<boolean, BdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("is_diagnostic_logging_enabled") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Loads user preferences from disk.
 * Returns default preferences if the file doesn't exist.
 */
async loadPreferences() : Promise<Result<AppPreferences, BdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("load_preferences") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Saves user preferences to disk.
 * Uses atomic write (temp file + rename) to prevent corruption.
 */
async savePreferences(preferences: AppPreferences) : Promise<Result<null, BdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_preferences", { preferences }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Sends a native system notification.
 * On mobile platforms, returns an error as notifications are not yet supported.
 */
async sendNativeNotification(title: string, body: string | null) : Promise<Result<null, BdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("send_native_notification", { title, body }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Saves emergency data to a JSON file for later recovery.
 * Validates filename and enforces a 10MB size limit.
 */
async saveEmergencyData(filename: string, data: JsonValue) : Promise<Result<null, BdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_emergency_data", { filename, data }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Loads emergency data from a previously saved JSON file.
 * Returns `BdError::NotFound` if the file doesn't exist.
 */
async loadEmergencyData(filename: string) : Promise<Result<JsonValue, BdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("load_emergency_data", { filename }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Removes recovery files older than 7 days.
 * Returns the count of removed files.
 */
async cleanupOldRecoveryFiles() : Promise<Result<number, BdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cleanup_old_recovery_files") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Shows the quick pane window and makes it the key window (for keyboard input).
 */
async showQuickPane() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("show_quick_pane") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Dismisses the quick pane window.
 * On macOS, resigns key window status before hiding to avoid activating main window.
 */
async dismissQuickPane() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("dismiss_quick_pane") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Toggles the quick pane window visibility.
 */
async toggleQuickPane() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("toggle_quick_pane") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Returns the default shortcut constant for frontend use.
 */
async getDefaultQuickPaneShortcut() : Promise<string> {
    return await TAURI_INVOKE("get_default_quick_pane_shortcut");
},
/**
 * Updates the global shortcut for the quick pane.
 * Pass None to reset to default.
 */
async updateQuickPaneShortcut(shortcut: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_quick_pane_shortcut", { shortcut }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * `#[tauri::command]` wrapper for `run_bd`. Takes the args and cwd
 * over the bridge as owned `String`s because the tauri-specta IPC
 * layer requires owned types; we borrow back to `&str` for the
 * runner.
 */
async runBdCommand(args: string[], cwd: string) : Promise<Result<BdOutput, BdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("run_bd_command", { args, cwd }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * `#[tauri::command]` wrapper for `check_bd_version`. Returns the
 * version as a `"major.minor.patch"` string so the frontend can
 * display it directly without reformatting.
 */
async checkBdVersionCmd() : Promise<Result<string, BdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("check_bd_version_cmd") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * `#[tauri::command]` wrapper for `check_schema_version`.
 */
async checkSchemaVersionCmd(cwd: string) : Promise<Result<number, BdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("check_schema_version_cmd", { cwd }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async readIssuesJsonl(cwd: string) : Promise<Result<JsonlResult, BdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("read_issues_jsonl", { cwd }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command wrapper for `detect`. Returns the aggregated
 * `BdInfo` to the frontend; never returns `Err` for the
 * "workspace not initialized" case (that's `Backend::Unknown`).
 * `Err` is reserved for "could not even invoke `bd`", which
 * surfaces as `BdError::BdNotInPath` and triggers the
 * "install beads" message in the modal.
 */
async detectBd(cwd: string) : Promise<Result<BdInfo, BdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("detect_bd", { cwd }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Adds a path to the recent-repositories list and persists preferences.
 * 
 * Dedup: if `path` is already present, it is moved to the top (most
 * recent) instead of being appended. After dedup, the list is capped at
 * [`MAX_RECENT_REPOS`].
 */
async addRecentRepo(path: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_recent_repo", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Returns the current working directory as a UTF-8 string.
 * 
 * Tauri 2.11's `PathResolver` does not expose a `current_dir()` method
 * (unlike the JS-side `@tauri-apps/api/path`), so we wrap
 * `std::env::current_dir()` in a tauri command. Used by the bootstrap
 * screen's "Use CWD" link.
 */
async getCurrentDir() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_current_dir") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Return the merged workspace list.
 * 
 * `current` is the active workspace's path (passed by the frontend
 * from the `workspace-store.repoPath`); pass `null` from JS when no
 * workspace is open yet. The Rust side treats both `null` and
 * missing files as "no current workspace" and skips the
 * always-first entry.
 */
async listWorkspaces(current: string | null) : Promise<Result<WorkspaceEntry[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_workspaces", { current }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Run `bd ready --json` in `cwd` and return the list of ready issues.
 */
async bdReady(cwd: string) : Promise<Result<Issue[], BdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("bd_ready", { cwd }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Run `bd blocked --json` in `cwd` and return the list of blocked issues.
 * 
 * **Implementation note (M3 R8):** `bd blocked --json` returns a
 * sparser shape than `bd list --json` — it omits `dependency_count`
 * and `dependent_count`, only emitting `blocked_by_count` and
 * `blocked_by` (array of IDs). Without those counts, every row's
 * `DependencyBadge` renders with counts of 0, which silently
 * drops the "blocks N" chip for an issue that has zero incoming
 * blockers but blocks others (TASK_REFAC in the fixture is one).
 * We delegate to `bd list --json` and filter to the same set
 * `bd blocked` would have returned: issues whose status is
 * `blocked` (manually-marked) OR that have at least one open
 * blocker (`dependency_count > 0`).
 */
async bdBlocked(cwd: string) : Promise<Result<Issue[], BdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("bd_blocked", { cwd }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Run `bd search <query> --json` in `cwd` and return matching issues.
 */
async bdSearch(cwd: string, query: string) : Promise<Result<Issue[], BdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("bd_search", { cwd, query }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Run `bd query <query> --json` in `cwd` and return matching issues.
 */
async bdQuery(cwd: string, query: string) : Promise<Result<Issue[], BdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("bd_query", { cwd, query }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Run `bd list <filters> --json` in `cwd` and return the matching issues.
 * 
 * `ListFilters::to_args` produces the flag argv; the runner's envelope
 * parsing kicks in because we append `--json`. The envelope's `data`
 * field is decoded into `Vec<Issue>` by `search_query::extract_data`
 * (made `pub(super)` for this caller).
 */
async bdList(cwd: string, filters: ListFilters) : Promise<Result<Issue[], BdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("bd_list", { cwd, filters }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Run `bd list --all --json` in `cwd` and return a `Graph` with
 * one node per issue and one edge per `Dependency` row.
 * 
 * Edge direction follows `Dependency` semantics: each edge points
 * from the dependent issue (the enclosing `Issue.id`) TO the
 * issue being depended on (`Dependency.dependency_id`). The
 * frontend reverses this for arrow rendering when it wants
 * "X blocks Y" semantics.
 */
async bdGraph(cwd: string) : Promise<Result<Graph, BdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("bd_graph", { cwd }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Run `bd create <flags> --json` in `cwd` and return the new issue.
 * 
 * Verified shape (bd 1.0.5, 2026-06-17): `{ schema_version: 1,
 * data: [Issue] }` — a 1-element array. The robust parser also
 * accepts a bare `data: {Issue}` object to cover CLI variants.
 * 
 * Empty `data: []` → `ParseError` so the frontend surfaces a
 * typed signal rather than silently dropping the result.
 */
async bdCreate(cwd: string, input: CreateInput) : Promise<Result<Issue, BdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("bd_create", { cwd, input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Run `bd update <id> <flags> --json` in `cwd` and return the
 * updated issue.
 * 
 * Same envelope shape as `bd create` (1-element array under `data`).
 * The robust parser handles the bare-object CLI variant as well.
 */
async bdUpdate(cwd: string, id: string, input: UpdateInput) : Promise<Result<Issue, BdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("bd_update", { cwd, id, input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Run `bd close <id> --json` in `cwd` and return the closed issue.
 * 
 * Verified shape (bd 1.0.5, 2026-06-17): `data: [Issue]` — the
 * closed issue with `status: "closed"`, `closed_at`, and a
 * `close_reason` field the runner ignores. The robust parser
 * accepts the bare-object variant.
 */
async bdClose(cwd: string, id: string) : Promise<Result<Issue, BdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("bd_close", { cwd, id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Run `bd reopen <id> --json` in `cwd` and return the reopened
 * issue.
 * 
 * Verified shape (bd 1.0.5, 2026-06-17): `data: [Issue]` — the
 * reopened issue with `status: "open"` and `closed_at: null`.
 * The robust parser accepts the bare-object variant.
 */
async bdReopen(cwd: string, id: string) : Promise<Result<Issue, BdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("bd_reopen", { cwd, id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Run `bd delete <id> --force --json` in `cwd` and return ().
 * 
 * `--force` is required: without it, `bd` prints a "DELETE PREVIEW"
 * warning and exits non-zero (the frontend's typed-identifier
 * confirmation in `IssueActions` is the equivalent safety check on
 * our side).
 * 
 * Verified shape (bd 1.0.5, 2026-06-17): `{ deleted, dependencies_removed,
 * references_updated, schema_version: 1 }` — a summary object, NOT
 * `data: [Issue]`. The runner already returns an error on non-zero
 * exit, so reaching `Ok(())` means the CLI accepted the delete and
 * produced parseable JSON. We don't try to decode the summary; the
 * frontend refetches the issue list and the deleted id disappears.
 */
async bdDelete(cwd: string, id: string) : Promise<Result<null, BdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("bd_delete", { cwd, id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Run `bd show <id> --json` in `cwd` and return the issue's
 * dependency list.
 * 
 * The dependency list is sourced from `bd show` (not `bd dep list`)
 * because the `Issue` struct already carries a typed
 * `dependencies: Vec<Dependency>` field (T2). The `bd show` envelope
 * returns `data: [Issue]` (1-element array) — same shape the rest
 * of the mutations module handles — and we pluck
 * `issue.dependencies` out of the lone element. The `bd dep list`
 * command emits a wider dependency record (with `from` / `to` /
 * `direction` columns the `Dependency` struct doesn't model) and
 * would force a second Raw struct just to drop those fields.
 * 
 * ponytail: defensive — accepts both `data: [Issue]` (the real
 * 1.0.5 shape) and `data: {Issue}` (the bare-object CLI variant
 * some 1.0.x builds emit). Empty `data: []` → `ParseError` so the
 * frontend gets a typed signal rather than silently returning an
 * empty vec for a deleted id.
 */
async bdDepList(cwd: string, id: string) : Promise<Result<Dependency[], BdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("bd_dep_list", { cwd, id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Run `bd dep add <from> <to> --type <type> --json` in `cwd`.
 * 
 * The CLI's `--type` flag takes the kebab-case form
 * (`parent-child`, `discovered-from`, …) per the dep help text,
 * NOT the snake_case form the Rust enum serializes to via
 * `serde(rename_all = "snake_case")`. The match below is the
 * authoritative mapping — keep it aligned with the `DependencyType`
 * variants added in T2.
 * 
 * The CLI does not return a typed JSON envelope on success — the
 * runner's `BdOutput::Text` ("Added dependency from … to …") and
 * `BdOutput::Json` (rare, undocumented summary) both count as
 * success. Reaching `Ok(())` means the runner saw a zero exit and
 * parseable output; the frontend refetches the dep list and the
 * new edge appears.
 */
async bdDepAdd(cwd: string, fromId: string, toId: string, depType: DependencyType) : Promise<Result<null, BdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("bd_dep_add", { cwd, fromId, toId, depType }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Run `bd dep remove <from> <to> --json` in `cwd`.
 * 
 * Same "any output is success" contract as `bd_dep_add`. The CLI
 * prints a one-line confirmation on success and exits non-zero if
 * the dependency doesn't exist; both paths flow through the
 * runner's normal exit-code handling.
 */
async bdDepRemove(cwd: string, fromId: string, toId: string) : Promise<Result<null, BdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("bd_dep_remove", { cwd, fromId, toId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Run `bd dep tree <id> --json` in `cwd` and return the dependency
 * tree as a flat list.
 * 
 * ponytail: the real `bd dep tree` CLI (1.0.5) may return a
 * nested `children: []` shape, or a flat list. v1 returns a flat
 * `Vec<Dependency>` for the lazy version — the frontend groups
 * rows by `from_id == issueId` (outgoing) and renders a depth-3
 * hierarchy from the flat list. If the CLI doesn't expose
 * `bd dep tree` in a future version, the lazy fallback is to
 * derive from `bd_show` recursively (TBD; current 1.0.5 ships
 * the command).
 * 
 * Accepts both a bare array (`[Dependency, ...]`) and the
 * standard envelope shape (`{ data: [Dependency, ...] }`).
 * Missing `data` is a `ParseError`; an empty `data: []` is a
 * valid empty tree (returns `Ok(vec![])`).
 */
async bdDepTree(cwd: string, id: string) : Promise<Result<Dependency[], BdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("bd_dep_tree", { cwd, id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Check whether adding `from -> to` would create a cycle. Returns
 * `true` if a cycle would be introduced.
 * 
 * ponytail: v1 returns `Ok(false)` unconditionally. The `bd`
 * CLI 1.0.5 doesn't expose a dedicated dry-run check command
 * (`bd dep check`, `bd dep add --dry-run`, etc. are not
 * available). Real cycle detection happens at write time —
 * `bd dep add` itself returns a non-zero exit with a cycle
 * error message if the new edge would close a loop, and the
 * runner surfaces that as `BdError::NonZeroExit`. The frontend
 * (T32's `CycleWarning`) treats the post-add error as the
 * authoritative signal. This command exists for the future v2
 * case where a real CLI probe ships, so the frontend
 * integration point doesn't have to change.
 */
async bdDepCheckCycle(cwd: string, fromId: string, toId: string) : Promise<Result<boolean, BdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("bd_dep_check_cycle", { cwd, fromId, toId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Run `bd label add <issue_id> <label> --json` in `cwd`.
 * 
 * The CLI returns a JSON array of per-target entries
 * `[{ issue_id, label, status: "added" }]` — we don't model
 * per-target summaries because v1 always targets a single issue
 * (the frontend calls this command once per label). The runner
 * surfaces a non-zero exit as `BdError::NonZeroExit`, so reaching
 * `Ok(())` means the CLI accepted the add and produced parseable
 * output. The frontend refetches the issue detail (the
 * `Issue.labels` field on `bd show`) and the new label appears.
 */
async bdLabelAdd(cwd: string, issueId: string, label: string) : Promise<Result<null, BdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("bd_label_add", { cwd, issueId, label }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Run `bd label remove <issue_id> <label> --json` in `cwd`.
 * 
 * Symmetric to `bd_label_add`: same "any output is success"
 * contract, same per-target JSON shape. Reaching `Ok(())` means
 * the CLI accepted the remove and the frontend's `bd show`
 * refetch will reflect the change.
 */
async bdLabelRemove(cwd: string, issueId: string, label: string) : Promise<Result<null, BdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("bd_label_remove", { cwd, issueId, label }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Run `bd label propagate <parent> <label> --json` in `cwd` and
 * return a `PropagationReport` summary.
 * 
 * The real CLI (1.0.5, 2026-06-17) returns a flat array of
 * per-child entries `[{ issue_id, label, status: "added" |
 * "skipped" }, ...]`. Children that already carry the label are
 * reported as `skipped`; children that don't are `added`. We
 * flatten the per-child rows into a `{ added, skipped, errors }`
 * summary — the frontend's toast only needs the totals.
 * 
 * `errors` is for the unexpected statuses / shapes — the runner's
 * `BdError` already covers the "non-zero exit" path (e.g. parent
 * has no children at all), so a non-empty `errors` vec indicates
 * the CLI ran but reported something the v1 mapper doesn't
 * recognise.
 * 
 * ponytail: a parent with no children is the most common case in
 * v1 (most issues are leaves) and the CLI returns `[]`. The
 * mapper yields `{ added: 0, skipped: 0, errors: [] }` — the
 * frontend's "Propagated 0 children" toast is the expected user
 * signal, not an error.
 */
async bdLabelPropagate(cwd: string, parentId: string, label: string) : Promise<Result<PropagationReport, BdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("bd_label_propagate", { cwd, parentId, label }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Run `bd label list-all --json` in `cwd` and return the sorted
 * list of `(label, count)` rows.
 * 
 * The real CLI (1.0.5, 2026-06-17) emits a bare array
 * `[{ label, count }, ...]` — no `data` envelope wrapper. Each
 * row carries the label name and the number of issues currently
 * carrying it (the v1 source of truth for the "usage count" the
 * frontend renders next to each label).
 * 
 * ponytail: the prompt's stub typed the return as
 * `Vec<String>`. The plan T35 AC ("List renders with usage
 * counts") and the real CLI shape make that lossy — we'd either
 * drop `count` or compute it client-side via N+1 `bd list` calls.
 * `LabelWithCount { label, count }` is the honest shape; sorted
 * by name on the Rust side so the frontend renders in a stable
 * order without re-sorting.
 */
async bdLabelListAll(cwd: string) : Promise<Result<LabelWithCount[], BdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("bd_label_list_all", { cwd }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Run `bd list --json` (no filters) in `cwd` and return the sorted
 * list of distinct `(assignee, count)` rows.
 * 
 * The Beads CLI (1.0.5, 2026-06-17) does NOT expose an
 * `assignee list-all` subcommand, so we derive the distinct
 * `(owner, count)` pairs from a full `bd list --json` pass on
 * the Rust side. This is a small bounded concern: we do not
 * read `.beads/issues.jsonl` directly (per the constitution
 * rule — `bd` is the single source of truth), we shell out to
 * `bd list --json` once and aggregate in-memory.
 * 
 * Unassigned issues (`owner = None`) are intentionally excluded
 * from the returned rows. The frontend renders an explicit
 * "Unassigned" toggle only when the user opts in (separate
 * from this list) — surfacing a synthetic "" (empty string)
 * row would clutter the sidebar.
 * 
 * The rows are sorted by `assignee` on the Rust side so the
 * frontend renders in a stable order without re-sorting
 * (same convention as `bd_label_list_all`).
 */
async bdAssigneeListAll(cwd: string) : Promise<Result<AssigneeWithCount[], BdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("bd_assignee_list_all", { cwd }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Send a desktop notification (uses `tauri-plugin-notification`).
 * 
 * ponytail: thin no-op stub. v1 callers (the `useNotifications` hook
 * in `src/hooks/useNotifications.ts`) wrap this in a best-effort
 * `try/catch` and don't surface failures to the UI. Wiring the real
 * `tauri-plugin-notification` API is a future task — the contract
 * from the TS side is positional `(title, body)` and a `Result<null,
 * String>` shape, exactly matching tauri-specta's default export.
 */
async bdNotify(title: string, body: string) : Promise<Result<null, BdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("bd_notify", { title, body }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Run `bd show <id> --json` in `cwd` and return the matching `Issue`.
 * 
 * `bd show` returns `data` as a 1-element array; we take the first.
 * Returns `ParseError` if the array is empty (should not happen for
 * a valid id, but possible for a race with `bd delete`).
 * 
 * **bd show JSON is sparser than the list JSON** (verified against
 * bd 1.0.4, 2026-06-24): it omits `dependency_count`,
 * `dependent_count`, `comment_count`, and (for issues without
 * those) `description`, `owner`, `closed_at`, `parent`,
 * `acceptance_criteria`, `external_ref`, and the full
 * `dependencies` list. The `Issue` struct has `#[serde(default)]`
 * on every field `bd show` may omit, so the deserialiser fills
 * them with the documented defaults and the command succeeds.
 * 
 * **M3 R8 backfill:** `bd show` ALSO omits the summary
 * `dependency_count` / `dependent_count` fields that the list
 * envelope emits. Without backfill, the detail drawer's
 * `DependencyBadge` always renders with counts of 0 — which
 * silently drops the "blocks N" chip for an issue that has zero
 * incoming blockers but blocks others (TASK_REFAC in the fixture
 * is one). The R8 E2E spec
 * (`renders a header dep badge in the detail drawer for a
 * blocked issue`) trips on this. We backfill from the
 * `dependencies` / `dependents` arrays bd show DOES emit,
 * excluding `parent-child` edges to mirror the count semantics
 * `bd list --json` already applies (parent-child is structural,
 * not blocking).
 */
async bdShow(cwd: string, id: string) : Promise<Result<Issue, BdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("bd_show", { cwd, id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Run `bd history <id> --json` in `cwd` and return the issue's
 * history entries (one per Dolt commit, oldest-last as emitted by
 * the CLI).
 */
async bdHistory(cwd: string, id: string) : Promise<Result<HistoryEntry[], BdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("bd_history", { cwd, id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Run `bd comments <id> --json` in `cwd` and return the comments.
 */
async bdComments(cwd: string, id: string) : Promise<Result<Comment[], BdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("bd_comments", { cwd, id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Run `bd comment <id> "<body>"` in `cwd` to append a comment.
 * 
 * The CLI prints a one-line success message on stdout (no `--json`
 * flag is available for this write path), so any `BdOutput` variant
 * is treated as success — the runner's `NonZeroExit` handles real
 * failures (id not found, body validation, etc.).
 */
async bdAddComment(cwd: string, id: string, body: string) : Promise<Result<null, BdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("bd_add_comment", { cwd, id, body }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Run `bd statuses --json` in `cwd` and return the merged catalog.
 * 
 * Beads has no dedicated `--cwd` arg — the CLI auto-discovers
 * `.beads/` from the working directory. We hand it the repo path
 * directly (per the constitution's "bd is the single source of
 * truth" rule) so a multi-workspace switcher's `cwd` propagates
 * to the catalog query without each component re-deriving it.
 */
async bdStatuses(cwd: string) : Promise<Result<StatusCatalog, BdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("bd_statuses", { cwd }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Run `bd gate list [--all] --json` in `cwd` and return the parsed
 * entries. Default scope is open gates (matching the CLI's own
 * default); pass `include_closed: true` to opt into the full
 * history view.
 */
async bdGateList(cwd: string, includeClosed: boolean | null) : Promise<Result<GateEntry[], BdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("bd_gate_list", { cwd, includeClosed }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: replace the live beads watcher with one rooted
 * at `repo_path`. Called from the React side whenever the active
 * repo changes so `beads-issue-*` events carry the right
 * `repo_path` payload (the frontend filters on
 * `event.payload.repo_path === activeRepoPath`).
 */
async attachWatchRepo(repoPath: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("attach_watch_repo", { repoPath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

/**
 * Application preferences that persist to disk.
 * Only contains settings that should be saved between sessions.
 */
export type AppPreferences = { theme: string; 
/**
 * Global shortcut for quick pane (e.g., "CommandOrControl+Shift+.")
 * If None, uses the default shortcut
 */
quick_pane_shortcut: string | null; 
/**
 * User's preferred language (e.g., "en", "es", "de")
 * If None, uses system locale detection
 */
language: string | null; 
/**
 * Recently-opened beads repository paths, most-recent first. Capped at 10.
 * `#[serde(default)]` so old `preferences.json` files written before this
 * field existed still deserialize (they predate the bootstrap flow).
 */
recent_repos?: string[]; 
/**
 * Optional override for the `bd` executable path. When `None`,
 * the runner falls back to `PATH` lookup. `#[serde(default)]`
 * keeps pre-existing `preferences.json` files loadable. Used by
 * the SettingsPanel (T50) for non-standard installs (mise/asdf
 * shims, custom builds).
 */
bd_path?: string | null; 
/**
 * Optional override for the default per-command timeout in
 * seconds. When `None`, the runner uses its built-in 10s
 * default. `#[serde(default)]` for backward compatibility.
 * Range validated by the SettingsPanel (1-60); out-of-range
 * values here are accepted by the loader and ignored by the
 * runner (it clamps to its own min/max).
 */
default_timeout_secs?: number | null }
/**
 * One row of `bd_assignee_list_all` — distinct owner (assignee)
 * across the whole `.beads/` database, with the count of issues
 * they own.
 * 
 * Mirror of `LabelWithCount`: the Beads CLI (v1.0.5) does not
 * expose an `assignee list-all` subcommand, so we derive the
 * distinct `(owner, count)` pairs from a full `bd list --json`
 * pass on the Rust side. Sorted by name so the frontend renders
 * in a stable order without re-sorting.
 * 
 * `count` is the number of issues currently owned by that user.
 * Unassigned issues (`owner = None`) are NOT included — the
 * frontend renders an explicit "Unassigned" affordance only when
 * the user actively opts in (separate from this list).
 * 
 * ponytail: the struct shape is intentionally identical to
 * `LabelWithCount { label, count }` rather than a richer
 * `Assignee { name, email, ... }`. Beads' owner model in v1 is
 * just a string with no metadata; a richer struct would force
 * `Option::None`s everywhere today and constrain a v2 metadata
 * shape prematurely. Reuse the flat shape; expand when a real
 * metadata field lands.
 */
export type AssigneeWithCount = { assignee: string; count: number }
/**
 * Which on-disk store the workspace uses. `Unknown` means we found
 * `.beads/` (or its directory is missing) but couldn't classify it
 * — the modal layer (T10) treats this the same as "no compatible
 * workspace" and prompts the user to run `bd init`.
 */
export type Backend = 
/**
 * Workspace writes issues to a `.jsonl` file in `.beads/`.
 */
"jsonl" | 
/**
 * Workspace uses a Dolt SQL backend (no JSONL file).
 */
"dolt" | 
/**
 * `.beads/` exists but neither a JSONL file nor a `backend: dolt`
 * config was found.
 */
"unknown"
export type BdError = { type: "NotFound"; id: string } | { type: "SchemaMismatch"; message: string } | { type: "BdNotInPath" } | { type: "Timeout"; seconds: number } | { type: "NonZeroExit"; code: number; stdout: string; stderr: string } | { type: "PermissionDenied"; path: string } | { type: "DoltOnly"; message: string } | { type: "ParseError"; message: string } | { type: "IoError"; message: string } | { type: "AlreadyLocked"; repo_path: string } | { type: "NotARepo"; path: string }
/**
 * Aggregated facts about a Beads workspace, returned by `detect`.
 * All fields are populated even on partial failure so the modal can
 * show the user the most useful information (e.g. "bd is 2.5.0 but
 * we need 1.0–2.0", "no .beads/ directory", "workspace uses Dolt").
 */
export type BdInfo = { 
/**
 * `(major, minor, patch)` from `bd --version`. `None` if `bd`
 * is not on PATH or returned an unparseable version.
 */
version: [number, number, number] | null; 
/**
 * Schema version from the `bd list --json` envelope. `None` if
 * `bd` is not installed, not initialized, or returned legacy JSON.
 */
schema_version: number | null; 
/**
 * Path to the most recently modified `.beads/*.jsonl` file, or
 * `None` if no JSONL file exists (Dolt backend, fresh workspace,
 * or wrong directory).
 */
jsonl_path: string | null; 
/**
 * Detected on-disk store layout. See [`Backend`].
 */
backend: Backend }
/**
 * Output of a `bd` invocation. The JSON variant covers both the
 * `{ schema_version, data }` envelope (default for `bd >= 1.0.5`
 * with `BD_JSON_ENVELOPE=1`) and bare legacy JSON (pre-envelope CLI
 * behavior). The Text variant is the fallback for human-readable
 * commands like `bd --version`.
 */
export type BdOutput = { type: "json"; value: JsonValue } | { type: "text"; value: string }
export type Comment = { id: string; author: string; body: string; created_at: string; updated_at: string | null }
/**
 * Input struct for `bd create --json`.
 * 
 * Every field except `title` is optional; an empty `CreateInput`
 * (with a title) produces a minimal-issue create. Empty strings on
 * optional `String` fields are treated as "not set" so the frontend
 * can pass `""` without producing a no-op `--description ""` flag.
 * Each `Option<Vec<_>>` is repeatable on the CLI (`--label x --label y`).
 */
export type CreateInput = { 
/**
 * Required title. Maps to `bd create --title`.
 */
title: string; 
/**
 * Optional description. Maps to `bd create --description`. Empty
 * string is treated as "not set" to avoid emitting `--description ""`.
 */
description?: string | null; 
/**
 * Optional issue type. Maps to `bd create --type` (bare enum name,
 * e.g. `"bug"`, `"feature"`). If `None`, the CLI defaults to `"task"`.
 */
issueType?: IssueType | null; 
/**
 * Optional priority. Maps to `bd create --priority` as a bare
 * integer 0..4 (`IssuePriority` is `#[repr(u8)] Serialize_repr`).
 * If `None`, the CLI defaults to `2` (P2).
 */
priority?: IssuePriority | null; 
/**
 * Optional assignee / owner. Maps to `bd create --assignee`.
 * Empty string is treated as "not set".
 */
assignee?: string | null; 
/**
 * Optional labels. Maps to `bd create --label` (repeatable, one
 * `--label` flag per element).
 */
labels?: string[] | null; 
/**
 * Optional external reference (e.g. GitHub issue id). Maps to
 * `bd create --external-ref`. Empty string is treated as "not set".
 */
externalRef?: string | null }
export type Dependency = { 
/**
 * The target issue id (the issue being depended on, i.e. the
 * "to" side of the relationship). The field is named
 * `dependency_id` in the Rust→TS contract (see
 * `DependencyTreeView.tsx`) but `bd show --json` emits the
 * nested issue object under the `id` key (the entry is a
 * full issue, not a `{dependency_id, dependency_type}`
 * pair), and `bd list --json` historically used
 * `depends_on_id`. The two aliases keep all three shapes
 * deserialisable; serialization stays `dependency_id` so the
 * frontend contract is unchanged. The `issue_id` bd also
 * emits is the source side — that's already on the
 * enclosing `Issue`, so we just ignore it on deserialize
 * (serde_json drops unknown fields).
 */
dependency_id: string; 
/**
 * bd emits this as `type` (a reserved Rust keyword, hence the
 * Rust field rename). Alias keeps bd's output deserialisable;
 * serialization stays `dependency_type`.
 */
dependency_type: DependencyType; 
/**
 * `#[serde(default)]` because bd v1.0.4 does NOT emit a
 * `blocked_by` flag in `bd list --json` — that direction is
 * implicit from `type` (a `blocks` edge on a non-closed issue
 * means the source is blocked). Default = `None`.
 */
blocked_by?: boolean | null }
export type DependencyType = "blocks" | 
/**
 * bd v1.0.4 emits this as `parent-child` (kebab-case) instead of
 * the snake_case the enum's `rename_all` would produce. The
 * alias keeps bd's output deserialisable; serialization stays
 * `parent_child` so the existing TS contract is unchanged.
 */
"parent_child" | "conditional_blocks" | "waits_for" | "related" | "tracks" | "discovered_from" | "caused_by" | "validates" | "supersedes"
/**
 * One row of the `bd gate list --json` response.
 * 
 * The CLI (1.0.5) emits the same `{ id, title, status, priority,
 * issue_type, ... }` shape that `bd list --json` uses, just
 * filtered to `issue_type == "gate"`. We accept the full Issue
 * schema so the gates view can render every column the issue
 * list exposes (title, status pill, priority dot, age) without a
 * second IPC round-trip.
 * 
 * `is_closed` is derived on the Rust side from the status string
 * (via [`crate::beads::issue_status_is_closed`]) so the
 * frontend's open/closed toggle (a future follow-up) can branch
 * on a single boolean instead of string-matching `"closed"`.
 */
export type GateEntry = { issue: Issue; isClosed: boolean }
/**
 * The full graph payload. `nodes` are de-duplicated by id;
 * `edges` is the multiset of dependency rows from `bd list`
 * (with the source side filled in from the enclosing `Issue`).
 */
export type Graph = { nodes: GraphNode[]; edges: GraphEdge[] }
/**
 * One directed edge in the dependency graph. `source` is the
 * dependent issue (the one that "needs" `target`); `target` is
 * the issue being depended on. `dep_type` is the raw bd edge
 * kind so the frontend can colour / dash it per type.
 */
export type GraphEdge = { source: string; target: string; depType: DependencyType }
/**
 * One node in the dependency graph. Carries just enough for the
 * frontend to render a labelled card and colour it by status /
 * type without another round-trip.
 */
export type GraphNode = { id: string; title: string; status: string; priority: IssuePriority; issueType: IssueType }
/**
 * One entry from an issue's version history.
 * 
 * Sourced from `bd history <id> --json`. The CLI returns one entry per
 * commit on the issue's Dolt history; each commit captures a snapshot of
 * the issue at that point in time. The fields exposed here are the
 * frontend-friendly projection of that snapshot — the raw Dolt fields
 * (`CommitHash` / `Committer` / `CommitDate` / nested `Issue` snapshot)
 * are mapped in `show_history::bd_history` via an internal `Raw` struct
 * so the public type stays clean.
 * 
 * `action` is derived from the snapshot's `status` (e.g. `"status: open"`)
 * because the real `bd history` JSON does not carry a discrete action
 * code — it gives you the state at each commit, not the transition. The
 * 16b `IssueDetailView` History tab can use `details` for the title/role
 * context.
 */
export type HistoryEntry = { 
/**
 * Commit hash from Dolt. Acts as the unique row id.
 */
id: string; 
/**
 * Issue id this entry belongs to.
 */
issueId: string; 
/**
 * When the commit was authored (UTC).
 */
timestamp: string; 
/**
 * Derived: the issue's status at this commit (e.g. `"status: open"`).
 */
action: string; 
/**
 * Dolt committer name. The CLI reports it for every entry, so the
 * field stays `Option` to keep room for future CLI variants that
 * might omit it.
 */
actor: string | null; 
/**
 * Free-form context: the issue title at the time of the commit, plus
 * the status. Helps the History tab render a useful one-liner.
 */
details?: string | null }
export type Issue = { id: string; title: string; status: string; priority: IssuePriority; issue_type: IssueType; created_at: string; 
/**
 * `#[serde(default)]` because bd v1.0.4's `bd list --json`
 * omits `updated_at` for issues that have never been updated
 * after creation. Default = `None`.
 */
updated_at?: string | null; 
/**
 * `#[serde(default)]` because bd only emits `closed_at` when
 * the issue is actually closed; open / in_progress issues have
 * no entry. Default = `None`.
 */
closed_at?: string | null; 
/**
 * `#[serde(default)]` because bd v1.0.4's list output omits
 * `description` for issues with no description. Default = `None`.
 */
description?: string | null; 
/**
 * `#[serde(default)]` because bd v1.0.4's list output omits
 * `owner` for unassigned issues. Default = `None`.
 */
owner?: string | null; 
/**
 * `#[serde(default)]` because bd v1.0.4's `bd list --json`
 * output omits `labels` entirely for issues that have no
 * labels attached (verified against `BD_JSON_ENVELOPE=1` output
 * from the CLI). Default = empty `Vec`. The M4 R9 E2E spec's
 * `make-second-fixture.sh` seeds five label-less issues; without
 * this default the list view for `/tmp/e2e-workspace-b` raised
 * "failed to parse issues from 'data' field: missing field
 * `labels`" and the r10 real-time sync smoke spec timed out on
 * the post-switch reload. Surfaced as a `ParseError` from
 * `bd_list` (`extract_data` in `search_query.rs`).
 */
labels?: Label[]; 
/**
 * `#[serde(default)]` because bd v1.0.4's `bd list --json`
 * output does NOT include a `dependencies` array — only the
 * `dependency_count` and `dependent_count` summary fields are
 * emitted. The full dependency list is only present in
 * `bd show --json`. Default = empty `Vec`. Surfaced as the
 * `missing field 'dependencies'` ParseError after the M0
 * label regression was fixed.
 */
dependencies?: Dependency[]; 
/**
 * Outgoing edges: issues that depend on THIS one (the
 * "blocks N" side). `bd show --json` emits these under
 * the `dependents` key as a list of nested issue objects
 * (each carries `dependency_type`), while `bd list --json`
 * omits the field entirely (the summary `dependent_count`
 * is sufficient for the list view). The R8 E2E spec
 * (`r8-dep-badges`) needs the detail drawer to surface
 * the "blocks N" chip for an issue that has zero incoming
 * blockers — TASK_REFAC is one — so the badge can render
 * with `dependent_count` derived from this array.
 * Default = empty `Vec`. Same `Dependency` shape as
 * `dependencies` (uses the `id` → `dependency_id` alias).
 */
dependents?: Dependency[]; 
/**
 * `#[serde(default)]` because bd v1.0.4's `bd show --json`
 * output omits `dependency_count` — the field is only present
 * in `bd list --json`. Default = `0`. The R4 E2E spec needs
 * the drawer to mount (which fails on `bd show` ParseError
 * without this default). The R8 E2E spec backfills this from
 * `dependencies.len()` in `bd_show` (excluding parent-child
 * edges, mirroring `bd list`'s own count semantics — see
 * `show_history::bd_show`), so an issue that has no incoming
 * blockers but blocks others still renders the right chip.
 */
dependency_count?: number; 
/**
 * `#[serde(default)]` because bd v1.0.4's `bd show --json`
 * output omits `dependent_count`. Default = `0`. Mirror of
 * `dependency_count` above.
 */
dependent_count?: number; 
/**
 * `#[serde(default)]` because bd v1.0.4's `bd show --json`
 * output omits `comment_count`. Default = `0`. Mirror of
 * `dependency_count` above.
 */
comment_count?: number; 
/**
 * `#[serde(default)]` because bd v1.0.4's list output omits
 * `parent` for issues that aren't children of an epic. Default
 * = `None`.
 */
parent?: string | null; 
/**
 * `#[serde(default)]` because bd v1.0.4's list output omits
 * `acceptance_criteria` for issues without a defined AC field.
 * Default = `None`.
 */
acceptance_criteria?: string | null; 
/**
 * `#[serde(default)]` because bd v1.0.4's list output omits
 * `external_ref` for issues without a linked external ticket.
 * Default = `None`.
 */
external_ref?: string | null }
export type IssuePriority = "P0" | "P1" | "P2" | "P3" | "P4"
export type IssueType = "bug" | "feature" | "task" | "epic" | "chore" | "decision" | "gate"
export type JsonValue = null | boolean | number | string | JsonValue[] | Partial<{ [key in string]: JsonValue }>
export type JsonlResult = { issues: Issue[]; skipped_lines: ([number, string])[] }
/**
 * A label attached to an issue. Beads v1 has no colour metadata
 * for labels, but the v1 `bd list --json` output may emit labels
 * as either a bare string (`"security"`) or a `{name, color}`
 * object depending on the CLI build. Both shapes are accepted by
 * the custom `Deserialize` impl below; serialization is unchanged
 * (the `Label { name, color }` shape). The frontend bindings
 * (specta-generated `bindings.ts`) keep the `Label` name.
 */
export type Label = { name: string; color: string | null }
/**
 * One row of `bd label list-all --json`.
 * 
 * The real CLI (1.0.5, 2026-06-17) emits a list of
 * `[{ label: "<name>", count: <u32> }, ...]` — no `data`
 * envelope wrapper, just a bare array. `count` is the number of
 * issues carrying the label, which is the v1 source of truth for
 * the "usage count" the frontend renders next to each label.
 * 
 * ponytail: I chose to model `count` as `u32` (the CLI's native
 * type) rather than a `Label` wrapper struct, because (a) the
 * CLI doesn't carry label colours (Beads labels are plain text —
 * see AGENTS.md / AC-12), so reusing the existing `Label { name,
 * color: Option<String> }` struct would force a `color: None`
 * everywhere, and (b) the `count` is a sibling of `label`, not a
 * derived field. A flat `LabelWithCount { label, count }` is the
 * honest shape; any future "label has metadata" expansion
 * becomes a new struct, not a v1 break.
 */
export type LabelWithCount = { label: string; count: number }
/**
 * Filter struct for `bd list --json`.
 * 
 * Every field is optional; an empty struct produces no filter arguments, and
 * the frontend can pass only the dimensions it actively filters by. Each
 * `Option<Vec<_>>` is repeatable on the CLI (`--status open --status closed`),
 * so passing multiple values is the natural shape.
 */
export type ListFilters = { 
/**
 * Filter by lifecycle status. Maps to `bd list --status` (repeatable).
 */
status?: string[] | null; 
/**
 * Filter by priority. Maps to `bd list --priority` (repeatable,
 * bare integer 0..4 — `IssuePriority` uses `Serialize_repr`).
 */
priority?: IssuePriority[] | null; 
/**
 * Filter by issue type. Maps to `bd list --type` (repeatable).
 */
issueType?: IssueType[] | null; 
/**
 * Filter by label name. Maps to `bd list --label` (repeatable).
 */
labels?: string[] | null; 
/**
 * Filter by assignee/owner. Maps to `bd list --assignee` (repeatable).
 */
assignees?: string[] | null; 
/**
 * Free-text search. Maps to `bd list --search` (single).
 * Empty string is treated as "not set" so the frontend can pass `""`
 * without producing a no-op `--search ""` flag.
 */
search?: string | null; 
/**
 * Maximum number of issues to return. Maps to `bd list --limit` (single).
 */
limit?: number | null }
/**
 * One log line written by the frontend.
 */
export type LogLine = { 
/**
 * Free-form level label. We trust the frontend to send
 * `info | warn | error | debug` and don't enforce a closed set
 * so the renderer can add a new level without an app rebuild.
 */
level: string; 
/**
 * Single-line message. Newlines are stripped at the writer so
 * the file stays grep-able.
 */
message: string; 
/**
 * Optional context blob. Serialized to JSON; absent values are
 * omitted (so the on-disk format stays compact).
 */
context?: JsonValue | null; 
/**
 * Optional source label, e.g. `"ErrorBoundary"` or
 * `"useBeadsInvalidation"`. Helps when several call sites hit
 * the same path.
 */
source?: string | null }
/**
 * Result of `bd label propagate <parent> <label> --json`.
 * 
 * The real CLI (1.0.5, 2026-06-17) returns a flat array of
 * per-child entries `[{ issue_id, label, status }, ...]`, where
 * `status` is `"added"` or `"skipped"` (children that already
 * carry the label are reported as `skipped`). The Rust command
 * flattens that array into a `PropagationReport { added, skipped,
 * errors }` summary — the frontend doesn't need the per-child
 * rows, just the totals for the toast message.
 * 
 * `errors` collects any non-`added`/`skipped` statuses (or
 * unexpected shapes) as their stringified representation. The
 * `added` + `skipped` counts cover the happy path; a non-empty
 * `errors` vec tells the frontend the propagate was partial.
 * 
 * ponytail: `Default` is kept on the struct (so the mapper can
 * `PropagationReport::default()` for the empty-array CLI case) but
 * the fields are NOT decorated with `#[serde(default)]`. All three
 * are always populated by the Rust mapper before crossing the
 * bridge, so the TS type keeps them as required fields
 * (`{ added, skipped, errors }`, not `{ added?, skipped?, errors? }`)
 * — the v1 contract is "always present".
 */
export type PropagationReport = { added: number; skipped: number; errors: string[] }
/**
 * The merged catalog. `builtin` keeps the CLI's lifecycle order
 * (open → in_progress → blocked → deferred → closed → pinned →
 * hooked) and `custom` is appended alphabetically by `name` so
 * the frontend renders a deterministic order without re-sorting.
 * 
 * `status_names` is the flat ordered list — every status the user
 * can pick from — produced by concatenating `builtin + custom`.
 * The frontend's `<select>` / sidebar chip row iterate over this
 * directly; the `KNOWN_STATUS_ORDER` arrays previously sprinkled
 * across components are replaced by reading this list.
 */
export type StatusCatalog = { builtin: StatusMeta[]; custom: StatusMeta[]; statusNames: string[] }
/**
 * One status the frontend renders — merged across the built-in and
 * custom halves of the catalog. `is_builtin` lets the UI render
 * built-ins with their canonical palette + i18n key while custom
 * statuses fall back to a neutral style + raw label.
 * 
 * `category` is the bd taxonomy (`active`, `wip`, `frozen`,
 * `done`) — surfaced verbatim to the frontend so a future
 * palette variant can key off it (e.g. tint frozen statuses with
 * a frost-blue).
 */
export type StatusMeta = { name: string; category: string; icon?: string | null; description?: string | null; isBuiltin: boolean }
/**
 * Input struct for `bd update <id> <flags> --json`.
 * 
 * Every field is `Option<T>`. The semantics: a `None` field is "don't
 * change" (the CLI is not invoked with that flag at all); a
 * `Some(value)` field is "set to this value". This matches the
 * dirty-detection contract on the React side: the panel only sends
 * fields the user actually edited.
 * 
 * **Label semantics (v1 simplification)**: the real `bd update` (1.0.5)
 * uses `--add-label` (repeatable) and `--remove-label` for label
 * edits — there is no "set the new full list" flag. The v1 frontend
 * does not expose label editing from this panel; the label field is
 * omitted from `UpdateInput` entirely. T34-T36 will add a dedicated
 * label-edit flow that computes the add/remove diff and calls the
 * right flags.
 * 
 * **Empty-string handling**: same as `CreateInput` — `Some("")` for
 * `description` / `assignee` / `external_ref` is treated as "not set"
 * so the frontend can pass the empty string from a cleared input
 * without emitting a no-op `--description ""` flag.
 */
export type UpdateInput = { 
/**
 * New title. Maps to `bd update --title`.
 */
title?: string | null; 
/**
 * New description. Maps to `bd update --description`. Empty
 * string is treated as "not set" (same as `CreateInput`).
 */
description?: string | null; 
/**
 * New issue type. Maps to `bd update --type` (bare enum name,
 * e.g. `"bug"`). `serde(rename_all = "snake_case")` produces the
 * form the CLI expects.
 */
issueType?: IssueType | null; 
/**
 * New priority. Maps to `bd update --priority` as a bare integer
 * 0..4 (`IssuePriority` is `#[repr(u8)] Serialize_repr`).
 */
priority?: IssuePriority | null; 
/**
 * New lifecycle status. Maps to `bd update --status` (bare enum
 * name, e.g. `"in_progress"`).
 */
status?: string | null; 
/**
 * New assignee. Maps to `bd update --assignee` (the CLI uses
 * `--assignee`, not `--owner`, even though the Rust `Issue` struct
 * exposes the field as `owner` — the JSON keys differ, the
 * flag-vs-attribute mismatch is intentional in the CLI). Empty
 * string is treated as "not set".
 */
assignee?: string | null; 
/**
 * New external reference. Maps to `bd update --external-ref`.
 * Empty string is treated as "not set".
 */
externalRef?: string | null }
/**
 * A single workspace the dropdown can switch to.
 */
export type WorkspaceEntry = { 
/**
 * Absolute path to the workspace root (the directory that
 * contains `.beads/`).
 */
path: string; 
/**
 * Last path component — the human-readable workspace name
 * rendered in the dropdown row.
 */
name: string; 
/**
 * Which discovery source listed this entry.
 */
source: WorkspaceSource; 
/**
 * `true` when the directory exists on disk **and** contains a
 * `.beads/` subdirectory. `false` entries are still rendered
 * (so the user sees stale paths and can clean up), but visually
 * marked so the UI can show a "missing" badge.
 */
exists: boolean }
/**
 * Where a workspace entry was discovered from. Used by the frontend
 * to render the source label (e.g. italicise "registry" entries) and
 * to preserve order when merging sources.
 */
export type WorkspaceSource = 
/**
 * The currently-active workspace. Always rendered first.
 */
"current" | 
/**
 * Recently opened — listed in `AppPreferences.recent_repos`.
 */
"recent" | 
/**
 * Listed in `~/.beads/registry.json` but not in recents.
 */
"registry"

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
