/// <reference types="mocha" />
/// <reference types="webdriverio" />
/**
 * M0 smoke E2E (spec R3).
 *
 * Given a fixture workspace (25 Beads issues across all statuses,
 * generated by scripts/make-fixture.sh),
 *   when the Collier app launches under tauri-driver and the user
 *        clicks "Use CWD" on the bootstrap screen,
 *     then the window title is "Collier"
 *     and  the issue list renders at least one row.
 *
 * Runs in CI under Xvfb (see .github/workflows/ci.yml). Local
 * execution requires `tauri-driver` + a built Collier binary --
 * not part of `bun run check:all`; E2E is its own CI job.
 *
 * Selectors target the `data-testid` attributes baked into
 * `src/components/beads/issues/IssueListView.tsx`,
 * `src/components/beads/bootstrap/RepoSelection.tsx`, and the
 * window title set in `src-tauri/tauri.conf.json` -- all stable
 * contracts between the frontend and this test.
 */

import { browser, expect, $, $$ } from '@wdio/globals'

describe('Collier M0 smoke', () => {
  it('launches with the Collier title and renders the fixture issue list', async () => {
    // -- Given/When: app launches (driver handles process spawn) --

    // Window title comes from tauri.conf.json -> app.windows[0].title
    // (and from index.html's <title>; both are "Collier"). Read
    // document.title via execute() because wdio 9's types dropped
    // the W3C getTitle shorthand -- both reach the same string in
    // a Tauri webview.
    const title = await browser.execute(() => document.title)
    expect(title).toBe('Collier')

    // The bootstrap screen (RepoSelection) gates the issue list.
    // When `bd` is on PATH and `.beads/` exists in CWD, the
    // "Use CWD" button appears -- click it to load the fixture.
    const useCwdButton = await $('[data-testid="use-cwd-button"]')
    await useCwdButton.waitForDisplayed({ timeout: 30_000 })
    await useCwdButton.click()

    // The issue list view is rendered once the Beads bootstrap
    // finishes loading the workspace (see IssueListView.tsx). Wait
    // for it -- Xvfb start + Dolt cold-start is ~2-5s on CI.
    const list = await $('[data-testid="issue-list-view"]')
    await list.waitForDisplayed({ timeout: 30_000 })

    // The fixture ships 25 issues (acceptance: >=1). Wait for at
    // least one row to mount before sampling the count.
    const firstRow = await $('[data-testid="issue-row"]')
    await firstRow.waitForDisplayed({ timeout: 30_000 })

    const rowCount = (await $$('[data-testid="issue-row"]')).length
    console.log(`[e2e] issue rows visible: ${rowCount}`)

    // -- Then: assertion from spec R3 --

    // At least 1 row is the smoke contract; the fixture provides
    // 25 to cover the "renders the real list" branch.
    expect(rowCount).toBeGreaterThanOrEqual(1)
  })
})
