/// <reference types="mocha" />
/// <reference types="webdriverio" />
/**
 * M0 smoke E2E (spec R3).
 *
 * Given a fixture workspace (25 Beads issues across all statuses,
 * generated by scripts/make-fixture.sh),
 *   when the Collier app launches under tauri-driver and the user
 *        clicks "Use CWD" on the bootstrap screen,
 *     then the window title is "Collier"
 *     and  the issue list renders at least one row.
 *
 * Runs in CI under Xvfb (see .github/workflows/ci.yml). Local
 * execution requires `tauri-driver` + a built Collier binary --
 * not part of `bun run check:all`; E2E is its own CI job.
 *
 * Selectors target the `data-testid` attributes baked into
 * `src/components/beads/issues/IssueListView.tsx`,
 * `src/components/beads/bootstrap/RepoSelection.tsx`, and the
 * window title set in `src-tauri/tauri.conf.json` -- all stable
 * contracts between the frontend and this test.
 *
 * The "open the fixture workspace" step lives in
 * `tests/e2e/helpers.ts` (`openFixtureWorkspace`) and is shared
 * with the M1 specs -- see that file for the isolation rationale.
 */

import { expect, $$ } from '@wdio/globals'

import { openFixtureWorkspace } from './helpers'

describe('Collier M0 smoke', () => {
  before(async () => {
    await openFixtureWorkspace('smoke')
  })

  it('renders at least one fixture issue row', async () => {
    // -- Then: assertion from spec R3 --
    //
    // At least 1 row is the smoke contract; the fixture provides
    // 25 to cover the "renders the real list" branch. The row
    // count is read from the live DOM rather than re-waiting on
    // the footer -- the helper above already blocked on the first
    // row, so any additional rows present are real.
    const rowCount = (await $$('[data-testid="issue-row"]')).length
    console.log(`[e2e:smoke] issue rows visible: ${rowCount}`)

    expect(rowCount).toBeGreaterThanOrEqual(1)
  })
})
