use tauri_specta::{collect_commands, Builder};

pub mod types;

pub fn generate_bindings() -> Builder<tauri::Wry> {
    use crate::beads::{
        detect, jsonl, list, lock, mutations, ready_blocked, runner, search_query, show_history,
    };
    use crate::commands::{notifications, preferences, quick_pane, recent_repos, recovery};

    Builder::<tauri::Wry>::new().commands(collect_commands![
        preferences::greet,
        preferences::load_preferences,
        preferences::save_preferences,
        notifications::send_native_notification,
        recovery::save_emergency_data,
        recovery::load_emergency_data,
        recovery::cleanup_old_recovery_files,
        quick_pane::show_quick_pane,
        quick_pane::dismiss_quick_pane,
        quick_pane::toggle_quick_pane,
        quick_pane::get_default_quick_pane_shortcut,
        quick_pane::update_quick_pane_shortcut,
        runner::run_bd_command,
        runner::check_bd_version_cmd,
        runner::check_schema_version_cmd,
        jsonl::read_issues_jsonl,
        lock::try_write_lock_cmd,
        detect::detect_bd,
        recent_repos::add_recent_repo,
        recent_repos::get_current_dir,
        ready_blocked::bd_ready,
        ready_blocked::bd_blocked,
        search_query::bd_search,
        search_query::bd_query,
        list::bd_list,
        mutations::bd_create,
        mutations::bd_update,
        mutations::bd_close,
        mutations::bd_reopen,
        mutations::bd_delete,
        mutations::bd_dep_list,
        mutations::bd_dep_add,
        mutations::bd_dep_remove,
        mutations::bd_dep_tree,
        mutations::bd_dep_check_cycle,
        mutations::bd_label_add,
        mutations::bd_label_remove,
        mutations::bd_label_propagate,
        mutations::bd_label_list_all,
        mutations::bd_notify,
        show_history::bd_show,
        show_history::bd_history,
        show_history::bd_comments,
        show_history::bd_add_comment,
    ])
}

/// Export TypeScript bindings to the frontend.
/// Run with: cargo test export_bindings -- --ignored
pub fn export_ts_bindings() {
    generate_bindings()
        .export(
            specta_typescript::Typescript::default()
                .header("// @ts-nocheck\n// Auto-generated by tauri-specta. DO NOT EDIT.\n\n")
                // `BdError::Timeout::seconds` is `u64`. Specta's default
                // BigInt behavior is `Fail`, which aborts the export
                // (and would break CI). Timeouts in this app are small
                // (10s runner, 2s lock), so `Number` is safe and keeps
                // the bridge as a plain `number` on the TS side.
                .bigint(specta_typescript::BigIntExportBehavior::Number),
            "../src/lib/bindings.ts",
        )
        .expect("Failed to export TypeScript bindings");
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Generate TypeScript bindings file.
    /// This test is ignored by default so it doesn't run in CI.
    /// Run manually with: cargo test export_bindings -- --ignored
    #[test]
    #[ignore]
    fn export_bindings() {
        export_ts_bindings();
        println!("✓ TypeScript bindings exported to ../src/lib/bindings.ts");
    }
}
